ERROR in src/app/data.service.ts(15,8): error TS2339: Property 'map' does not exist on type 'Observable<Response>'. 이란 메세지가 떠서 package.json 화일에     "rxjs": "^6.2.1",     "rxjs-compat": "^6.2.1", 수정하고, 추가했음. 나머지는 https://coursetro.com/posts/code/84/Setting-up-an-Angular-4-MEAN-Stack-(Tutorial) 따랐음..
commit push 후에 수정하는 방법은
http://animal-park.tistory.com/92
를 참고했음.